services:
  - type: web
    name: flask-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web.app:app
    autoDeploy: true

  - type: worker
    name: discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot/bot.py
    autoDeploy: true
